/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.praktikumpbo.projectbab8latihan;

/**
 *
 * @author Lenovo
 */
public class Kalkulator extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Kalkulator.class.getName());

    /**
     * Creates new form Kalkulator
     */
    double numEnter1, numEnter2, result;
    String operation;
    
    public Kalkulator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        numField = new javax.swing.JTextField();
        plusMinusButton = new javax.swing.JButton();
        clearEntryButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        sevenButton = new javax.swing.JButton();
        eightButton = new javax.swing.JButton();
        nineButton = new javax.swing.JButton();
        plusButton = new javax.swing.JButton();
        sixButton = new javax.swing.JButton();
        fourButton = new javax.swing.JButton();
        minusButton = new javax.swing.JButton();
        fiveButton = new javax.swing.JButton();
        divideButton = new javax.swing.JButton();
        equalToButton = new javax.swing.JButton();
        dotButton = new javax.swing.JButton();
        zeroButton = new javax.swing.JButton();
        oneButton = new javax.swing.JButton();
        twoButton = new javax.swing.JButton();
        threeButton = new javax.swing.JButton();
        multiplyButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        numField.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        numField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(numField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 270, 40));

        plusMinusButton.setBackground(new java.awt.Color(204, 204, 204));
        plusMinusButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        plusMinusButton.setText("±");
        plusMinusButton.setMaximumSize(new java.awt.Dimension(75, 75));
        plusMinusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusMinusButtonActionPerformed(evt);
            }
        });
        getContentPane().add(plusMinusButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 60, 60));

        clearEntryButton.setBackground(new java.awt.Color(204, 204, 204));
        clearEntryButton.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        clearEntryButton.setText("CE");
        clearEntryButton.setMaximumSize(new java.awt.Dimension(75, 75));
        clearEntryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearEntryButtonActionPerformed(evt);
            }
        });
        getContentPane().add(clearEntryButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 60, 60));

        clearButton.setBackground(new java.awt.Color(204, 204, 204));
        clearButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        clearButton.setText("C");
        clearButton.setMaximumSize(new java.awt.Dimension(75, 75));
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });
        getContentPane().add(clearButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 60, 60));

        sevenButton.setBackground(new java.awt.Color(204, 204, 204));
        sevenButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        sevenButton.setText("7");
        sevenButton.setMaximumSize(new java.awt.Dimension(75, 75));
        sevenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenButtonActionPerformed(evt);
            }
        });
        getContentPane().add(sevenButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 60, 60));

        eightButton.setBackground(new java.awt.Color(204, 204, 204));
        eightButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        eightButton.setText("8");
        eightButton.setMaximumSize(new java.awt.Dimension(75, 75));
        eightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightButtonActionPerformed(evt);
            }
        });
        getContentPane().add(eightButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 60, 60));

        nineButton.setBackground(new java.awt.Color(204, 204, 204));
        nineButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        nineButton.setText("9");
        nineButton.setMaximumSize(new java.awt.Dimension(75, 75));
        nineButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nineButtonActionPerformed(evt);
            }
        });
        getContentPane().add(nineButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 60, 60));

        plusButton.setBackground(new java.awt.Color(204, 204, 204));
        plusButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        plusButton.setText("+");
        plusButton.setMaximumSize(new java.awt.Dimension(75, 75));
        plusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusButtonActionPerformed(evt);
            }
        });
        getContentPane().add(plusButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 60, 60));

        sixButton.setBackground(new java.awt.Color(204, 204, 204));
        sixButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        sixButton.setText("6");
        sixButton.setMaximumSize(new java.awt.Dimension(75, 75));
        sixButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixButtonActionPerformed(evt);
            }
        });
        getContentPane().add(sixButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 60, 60));

        fourButton.setBackground(new java.awt.Color(204, 204, 204));
        fourButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        fourButton.setText("4");
        fourButton.setMaximumSize(new java.awt.Dimension(75, 75));
        fourButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourButtonActionPerformed(evt);
            }
        });
        getContentPane().add(fourButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 60, 60));

        minusButton.setBackground(new java.awt.Color(204, 204, 204));
        minusButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        minusButton.setText("-");
        minusButton.setMaximumSize(new java.awt.Dimension(75, 75));
        minusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minusButtonActionPerformed(evt);
            }
        });
        getContentPane().add(minusButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 60, 60));

        fiveButton.setBackground(new java.awt.Color(204, 204, 204));
        fiveButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        fiveButton.setText("5");
        fiveButton.setMaximumSize(new java.awt.Dimension(75, 75));
        fiveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveButtonActionPerformed(evt);
            }
        });
        getContentPane().add(fiveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 60, 60));

        divideButton.setBackground(new java.awt.Color(204, 204, 204));
        divideButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        divideButton.setText("/");
        divideButton.setMaximumSize(new java.awt.Dimension(75, 75));
        divideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divideButtonActionPerformed(evt);
            }
        });
        getContentPane().add(divideButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 60, 60));

        equalToButton.setBackground(new java.awt.Color(204, 204, 204));
        equalToButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        equalToButton.setText("=");
        equalToButton.setMaximumSize(new java.awt.Dimension(75, 75));
        equalToButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalToButtonActionPerformed(evt);
            }
        });
        getContentPane().add(equalToButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 60, 60));

        dotButton.setBackground(new java.awt.Color(204, 204, 204));
        dotButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        dotButton.setText(".");
        dotButton.setMaximumSize(new java.awt.Dimension(75, 75));
        dotButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dotButtonActionPerformed(evt);
            }
        });
        getContentPane().add(dotButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 60, 60));

        zeroButton.setBackground(new java.awt.Color(204, 204, 204));
        zeroButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        zeroButton.setText("0");
        zeroButton.setMaximumSize(new java.awt.Dimension(75, 75));
        zeroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroButtonActionPerformed(evt);
            }
        });
        getContentPane().add(zeroButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 60, 60));

        oneButton.setBackground(new java.awt.Color(204, 204, 204));
        oneButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        oneButton.setText("1");
        oneButton.setMaximumSize(new java.awt.Dimension(75, 75));
        oneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneButtonActionPerformed(evt);
            }
        });
        getContentPane().add(oneButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 60, 60));

        twoButton.setBackground(new java.awt.Color(204, 204, 204));
        twoButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        twoButton.setText("2");
        twoButton.setMaximumSize(new java.awt.Dimension(75, 75));
        twoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoButtonActionPerformed(evt);
            }
        });
        getContentPane().add(twoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 60, 60));

        threeButton.setBackground(new java.awt.Color(204, 204, 204));
        threeButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        threeButton.setText("3");
        threeButton.setMaximumSize(new java.awt.Dimension(75, 75));
        threeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(threeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 60, 60));

        multiplyButton.setBackground(new java.awt.Color(204, 204, 204));
        multiplyButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        multiplyButton.setText("*");
        multiplyButton.setMaximumSize(new java.awt.Dimension(75, 75));
        multiplyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplyButtonActionPerformed(evt);
            }
        });
        getContentPane().add(multiplyButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 60, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enterNumbers(String q){
        String nums = numField.getText() + q;
        numField.setText(nums);
    }
    
    private void minusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minusButtonActionPerformed
        numEnter1 = Double.parseDouble(numField.getText());
        numField.setText("");
        operation = "-";        
    }//GEN-LAST:event_minusButtonActionPerformed

    private void oneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneButtonActionPerformed
        enterNumbers("1");
    }//GEN-LAST:event_oneButtonActionPerformed

    private void twoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoButtonActionPerformed
        enterNumbers("2");
    }//GEN-LAST:event_twoButtonActionPerformed

    private void equalToButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalToButtonActionPerformed
        numEnter2 = Double.parseDouble(numField.getText());
        if (operation == "+") {
            result = numEnter1 + numEnter2; 
            numField.setText(String.valueOf(result));
        }
        else if (operation == "-") {
            result = numEnter1 - numEnter2; 
            numField.setText(String.valueOf(result));
        }
        else if (operation == "*") {
            result = numEnter1 * numEnter2; 
            numField.setText(String.valueOf(result));
        }
        else if (operation == "/") {
            result = numEnter1 / numEnter2; 
            numField.setText(String.valueOf(result));
        }
    }//GEN-LAST:event_equalToButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        numField.setText("");
    }//GEN-LAST:event_clearButtonActionPerformed

    private void sevenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenButtonActionPerformed
        enterNumbers("7");
    }//GEN-LAST:event_sevenButtonActionPerformed

    private void eightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightButtonActionPerformed
        enterNumbers("8");
    }//GEN-LAST:event_eightButtonActionPerformed

    private void nineButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nineButtonActionPerformed
        enterNumbers("9");
    }//GEN-LAST:event_nineButtonActionPerformed

    private void fourButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourButtonActionPerformed
        enterNumbers("4");
    }//GEN-LAST:event_fourButtonActionPerformed

    private void fiveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveButtonActionPerformed
        enterNumbers("5");
    }//GEN-LAST:event_fiveButtonActionPerformed

    private void sixButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixButtonActionPerformed
        enterNumbers("6");
    }//GEN-LAST:event_sixButtonActionPerformed

    private void threeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeButtonActionPerformed
        enterNumbers("3");
    }//GEN-LAST:event_threeButtonActionPerformed

    private void zeroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroButtonActionPerformed
        enterNumbers("0");
    }//GEN-LAST:event_zeroButtonActionPerformed

    private void divideButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divideButtonActionPerformed
        numEnter1 = Double.parseDouble(numField.getText());
        numField.setText("");
        operation = "/";
    }//GEN-LAST:event_divideButtonActionPerformed

    private void multiplyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplyButtonActionPerformed
        numEnter1 = Double.parseDouble(numField.getText());
        numField.setText("");
        operation = "*";
    }//GEN-LAST:event_multiplyButtonActionPerformed

    private void plusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusButtonActionPerformed
        numEnter1 = Double.parseDouble(numField.getText());
        numField.setText("");
        operation = "+";
    }//GEN-LAST:event_plusButtonActionPerformed

    private void clearEntryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearEntryButtonActionPerformed
        numField.setText("");
        
        String firstNum,secondNum;
        
        firstNum = String.valueOf(numEnter1);
        secondNum = String.valueOf(numEnter2);
        
        firstNum = "";
        secondNum = "";
    }//GEN-LAST:event_clearEntryButtonActionPerformed

    private void plusMinusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusMinusButtonActionPerformed
        double nums = Double.parseDouble(String.valueOf(numField.getText()));
        nums = nums * -1;
        numField.setText(String.valueOf(nums));
    }//GEN-LAST:event_plusMinusButtonActionPerformed

    private void dotButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dotButtonActionPerformed
        if (!numField.getText().contains(".")){
            numField.setText(numField.getText()+dotButton.getText());
        }
    }//GEN-LAST:event_dotButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Kalkulator().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearButton;
    private javax.swing.JButton clearEntryButton;
    private javax.swing.JButton divideButton;
    private javax.swing.JButton dotButton;
    private javax.swing.JButton eightButton;
    private javax.swing.JButton equalToButton;
    private javax.swing.JButton fiveButton;
    private javax.swing.JButton fourButton;
    private javax.swing.JButton minusButton;
    private javax.swing.JButton multiplyButton;
    private javax.swing.JButton nineButton;
    private javax.swing.JTextField numField;
    private javax.swing.JButton oneButton;
    private javax.swing.JButton plusButton;
    private javax.swing.JButton plusMinusButton;
    private javax.swing.JButton sevenButton;
    private javax.swing.JButton sixButton;
    private javax.swing.JButton threeButton;
    private javax.swing.JButton twoButton;
    private javax.swing.JButton zeroButton;
    // End of variables declaration//GEN-END:variables
}
