/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.gui2;
import javax.swing.table.*;
import javax.swing.JOptionPane;

/**
 *
 * @author fikry
 */
public class LihatDataPanel extends javax.swing.JPanel {

    /**
     * Creates new form LihatDataMahasiswa
     */
    public LihatDataPanel() {
        initComponents();
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mahasiswaTable = new javax.swing.JTable();
        updateButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Lihat Data Mahasiswa");

        mahasiswaTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(mahasiswaTable);

        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(updateButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 236, Short.MAX_VALUE)
                        .addComponent(updateButton)
                        .addGap(18, 18, 18)
                        .addComponent(deleteButton)
                        .addGap(25, 25, 25))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        int sel = mahasiswaTable.getSelectedRow();
        if(sel < 0){
            JOptionPane.showMessageDialog(this, "Pilih baris yang akan diupdate", "Info", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        String nim = (String) mahasiswaTable.getValueAt(sel, 1);
        Mahasiswa m = Mahasiswa.findByNim(nim);
        if(m == null) return;

        String newNama = JOptionPane.showInputDialog(this, "Nama:", m.getNama());
        if(newNama == null) return;
        newNama = newNama.trim();
        if(newNama.isEmpty()){
            JOptionPane.showMessageDialog(this, "Nama tidak boleh kosong", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String newNim = JOptionPane.showInputDialog(this, "NIM:", m.getNim());
        if(newNim == null) return;
        newNim = newNim.trim();
        if(newNim.isEmpty()){
            JOptionPane.showMessageDialog(this, "NIM tidak boleh kosong", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try { Long.parseLong(newNim); } catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "NIM harus angka", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(!newNim.equals(m.getNim()) && Mahasiswa.nimExists(newNim)){
            JOptionPane.showMessageDialog(this, "NIM sudah ada", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Object[] prodiOptions = {"S1 Teknik Informatika", "S1 Teknik Elektro", "D3 Teknik Elektro"};
        String newProdi = (String) JOptionPane.showInputDialog(this, "Pilih Prodi", "Prodi", JOptionPane.QUESTION_MESSAGE, null, prodiOptions, m.getProdi());
        if(newProdi == null) return;

        String[] jkOptions = {"Laki laki", "Perempuan"};
        String newJk = (String) JOptionPane.showInputDialog(this, "Pilih Jenis Kelamin", "JK", JOptionPane.QUESTION_MESSAGE, null, jkOptions, m.getJenisKelamin());
        if(newJk == null) return;

        int aktifConfirm = JOptionPane.showConfirmDialog(this, "Aktif?", "Status", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        boolean newActive = (aktifConfirm == JOptionPane.YES_OPTION);

        m.setNama(newNama);
        m.setNim(newNim);
        m.setProdi(newProdi);
        m.setJenisKelamin(newJk);
        m.setActive(newActive);

        loadData();
        JOptionPane.showMessageDialog(this, "Data berhasil diupdate");
    }//GEN-LAST:event_updateButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        int sel = mahasiswaTable.getSelectedRow();
        if(sel < 0){
            JOptionPane.showMessageDialog(this, "Pilih baris yang akan dihapus", "Info", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        String nim = (String) mahasiswaTable.getValueAt(sel, 1);
        Mahasiswa m = Mahasiswa.findByNim(nim);
        if(m == null) return;

        int confirm = JOptionPane.showConfirmDialog(this, "Hapus data mahasiswa NIM: " + nim + " ?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if(confirm == JOptionPane.YES_OPTION){
            Mahasiswa.mahasiswas.remove(m);
            loadData();
            JOptionPane.showMessageDialog(this, "Data dihapus");
        }
    }//GEN-LAST:event_deleteButtonActionPerformed
    
    private void loadData(){
        String[] column = {"Nama", "NIM", "Prodi", "Jenis Kelamin", "Status"};
        DefaultTableModel table = new DefaultTableModel(null, column){
            @Override
            public boolean isCellEditable(int row, int column){ return false; }
        };

        for (Mahasiswa mhs: Mahasiswa.mahasiswas){
            table.addRow(new String[]{
                mhs.getNama(), mhs.getNim(),
                mhs.getProdi(), mhs.getJenisKelamin(),
                mhs.isActive() ? "Aktif" : "Tidak Aktif"
            });
        }
        mahasiswaTable.setModel(table);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable mahasiswaTable;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
