/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package edu.praktikumpbo.projectbab9hasil;

/**
 *
 * @author Lenovo
 */
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
public class LihatDataPanel extends javax.swing.JPanel {
    
    private MainJFrame mainFrame; //utk referensi (biar changeMainPanel untuk panel update jalan(?)?
    public int barisTerpilih = -1;    
    
    public LihatDataPanel(MainJFrame mainFrame) {
        this.mainFrame = mainFrame;
        this.barisTerpilih = -1;
        initComponents();
        initTableListener();                        
        
    }
    
    private void initTableListener() {
        daftarMahasiswaTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                daftarMahasiswaTableMouseClicked(evt);
            }
        });
        
        daftarMahasiswaTable.setSelectionMode
        (javax.swing.ListSelectionModel.SINGLE_SELECTION);
    }
    
    private void daftarMahasiswaTableMouseClicked(java.awt.event.MouseEvent evt) {
        barisTerpilih = daftarMahasiswaTable.getSelectedRow();
        
        if (barisTerpilih != -1) {
            daftarMahasiswaTable.setRowSelectionInterval(barisTerpilih, 
                    barisTerpilih);
        }
    }           


    private void loadData(){
        String[] column = {"No.","Nama", "NIM", "Prodi", "Jenis Kelamin", 
            "Status"};
        DefaultTableModel table = new DefaultTableModel(null, column){
          @Override  
          public boolean isCellEditable(int row, int col){
              return false;
          }
        };
        
        int i = 1;        
        for (Mahasiswa mhs : Mahasiswa.mahasiswas) {
            
            table.addRow(new String[]{String.valueOf(i), mhs.getNama(), 
                mhs.getNim(), mhs.getProdi(), mhs.getJenisKelamin(),
            mhs.getIsActive() ? "Aktif" : "Tidak Aktif"});
            i++;
        }        
        daftarMahasiswaTable.setModel(table);
    }
    /**
     * Creates new form LihatDataPanel
     */


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        daftarMahasiswaTable = new javax.swing.JTable();
        updateButton = new javax.swing.JButton();
        hapusButton = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(515, 417));
        setPreferredSize(new java.awt.Dimension(515, 417));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setText("Lihat Data Mahasiswa");

        daftarMahasiswaTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(daftarMahasiswaTable);

        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        hapusButton.setText("Hapus");
        hapusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(updateButton)
                        .addGap(18, 18, 18)
                        .addComponent(hapusButton)))
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(updateButton)
                    .addComponent(hapusButton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        if (barisTerpilih == -1){
            JOptionPane.showMessageDialog(this, "Silahkan pilih data yang ingin di-update");
        } 
        else {
            String nama = daftarMahasiswaTable.getValueAt(barisTerpilih, 1).toString();
            String nim = daftarMahasiswaTable.getValueAt(barisTerpilih, 2).toString();
            String prodi = daftarMahasiswaTable.getValueAt(barisTerpilih, 3).toString();
            String jenisKelamin = daftarMahasiswaTable.getValueAt(barisTerpilih, 4).toString();
            String status = daftarMahasiswaTable.getValueAt(barisTerpilih, 5).toString();
            
            TambahDataPanel tambahPanel = new TambahDataPanel(mainFrame, barisTerpilih);
            tambahPanel.setModeUpdate(nama, nim, prodi, jenisKelamin, status);
            
            mainFrame.changeMainPanel(tambahPanel);
        }
    }
    

// 5. OPTIONAL: METHOD UNTUK RESET SELECTION
private void resetSelection() {
    barisTerpilih = -1;
    daftarMahasiswaTable.clearSelection();
            
        
    }//GEN-LAST:event_updateButtonActionPerformed

    private void hapusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusButtonActionPerformed
        // TODO add your handling code here:
            if (barisTerpilih == -1) {
            JOptionPane.showMessageDialog(this, 
                "Silahkan pilih data yang ingin dihapus");
        } else {
            String nama = daftarMahasiswaTable.getValueAt(barisTerpilih, 1).toString();

            int konfirmasi = JOptionPane.showConfirmDialog(this, 
                "Apakah Anda yakin ingin menghapus data mahasiswa:\n" + nama + "?", 
                "Konfirmasi Hapus",JOptionPane.YES_NO_OPTION);

            if (konfirmasi == JOptionPane.YES_OPTION) {
                Mahasiswa.mahasiswas.remove(barisTerpilih);                
                loadData();
                
                barisTerpilih = -1;
                JOptionPane.showMessageDialog(this,"Data mahasiswa berhasil dihapus!");
            }
        }
    }//GEN-LAST:event_hapusButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable daftarMahasiswaTable;
    private javax.swing.JButton hapusButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}

