/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package edu.praktikumpbo.projectbab9hasil;

import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class TambahDataPanel extends javax.swing.JPanel {

    private MainJFrame mainFrame;
    boolean isDalamUpdate;
    int barisTerpilih;
    
    public TambahDataPanel(MainJFrame mainFrame, int barisTerpilih) {
        this.mainFrame = mainFrame;
        this.barisTerpilih = barisTerpilih;
        initComponents();
    }
    
    
    /**
     * Creates new form TambahDataPanel
     */
    
    public void setModeUpdate(String nama, String nim, String prodi, 
            String jenisKelamin, String status) {
        tambahDataLabel.setText("Update Data Mahasiswa");
        namaTextField.setText(nama);
        nimTextField.setText(nim);
        prodiComboBox.setSelectedItem(prodi);
        if (jenisKelamin.equals("Laki-Laki")) {
            lakiLakiRadioButton.setSelected(true);
        } else {
            perempuanRadioButton.setSelected(true);
        }
        aktifCheckBox.setSelected(status.equals("Aktif"));

        this.isDalamUpdate = true;
    }
    private void clearForm(){
        namaTextField.setText("");
        nimTextField.setText("");
        lakiLakiRadioButton.setSelected(false);
        perempuanRadioButton.setSelected(false);
        aktifCheckBox.setSelected(false);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tambahDataLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        namaTextField = new javax.swing.JTextField();
        nimTextField = new javax.swing.JTextField();
        lakiLakiRadioButton = new javax.swing.JRadioButton();
        prodiComboBox = new javax.swing.JComboBox<>();
        perempuanRadioButton = new javax.swing.JRadioButton();
        aktifCheckBox = new javax.swing.JCheckBox();
        kirimButton = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        jPanel1.setMinimumSize(new java.awt.Dimension(515, 417));
        jPanel1.setPreferredSize(new java.awt.Dimension(515, 417));

        tambahDataLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        tambahDataLabel.setText("Tambah Data Mahasiswa");

        jLabel2.setText("Nama");

        jLabel3.setText("NIM");

        jLabel4.setText("Prodi");

        jLabel5.setText("Jenis Kelamin");

        jLabel6.setText("Status");

        namaTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        namaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaTextFieldActionPerformed(evt);
            }
        });

        nimTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        lakiLakiRadioButton.setText("Laki-Laki");
        lakiLakiRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lakiLakiRadioButtonActionPerformed(evt);
            }
        });

        prodiComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Teknik Informatika", "Teknik Elektro", "Teknik Sipil", "Teknik Lingkungan", "Teknik Kimia", "Teknik Mesin", "Arsitektur", " " }));
        prodiComboBox.setSelectedIndex(7);

        perempuanRadioButton.setText("Perempuan");
        perempuanRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perempuanRadioButtonActionPerformed(evt);
            }
        });

        aktifCheckBox.setText("Aktif");
        aktifCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aktifCheckBoxActionPerformed(evt);
            }
        });

        kirimButton.setBackground(new java.awt.Color(102, 102, 255));
        kirimButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        kirimButton.setForeground(new java.awt.Color(255, 250, 250));
        kirimButton.setText("Kirim");
        kirimButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kirimButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(namaTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nimTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
                            .addComponent(prodiComboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tambahDataLabel)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(aktifCheckBox)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lakiLakiRadioButton)
                                        .addGap(61, 61, 61)
                                        .addComponent(perempuanRadioButton))
                                    .addComponent(kirimButton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(tambahDataLabel)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(namaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nimTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(prodiComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lakiLakiRadioButton)
                    .addComponent(perempuanRadioButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(aktifCheckBox))
                .addGap(28, 28, 28)
                .addComponent(kirimButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void lakiLakiRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lakiLakiRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lakiLakiRadioButtonActionPerformed

    private void perempuanRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perempuanRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_perempuanRadioButtonActionPerformed

    private void aktifCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aktifCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aktifCheckBoxActionPerformed

    private void kirimButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kirimButtonActionPerformed
        // TODO add your handling code here:
        String nama = namaTextField.getText();
        String nim = nimTextField.getText();
        String prodi = (String) prodiComboBox.getSelectedItem();
        String jenisKelamin = lakiLakiRadioButton.isSelected() ? "Laki-Laki" : 
                perempuanRadioButton.isSelected() ? "Perempuan" : "";
        boolean isActive = aktifCheckBox.isSelected();
        
        if (nama.equals ("") || nim.equals("")){
            JOptionPane.showMessageDialog(this, "Gagal menambahkan data:\n"
                    + "- Nama atau NIM tidak terisi");
        }
        else if(jenisKelamin.equals("")){
            JOptionPane.showMessageDialog(this, "Gagal menambahkan data:\n"
                    + "- Opsi jenis kelamin belum dipilih");
        }
        else if(prodi.equals(" ")){
            JOptionPane.showMessageDialog(this, "Gagal menambahkan data:\n"
                    + "- Opsi prodi belum dipilih");
        }
        else if (!nama.matches("^[a-zA-Z ]+$")){
            JOptionPane.showMessageDialog(this, "Gagal menambahkan data:\n"
                    +"- Terdapat nomor atau karakter spesial pada Nama");
        }
        else if (nim.matches(".*[a-zA-Z].*") || nim.matches(".*[^a-zA-Z0-9].*")){
            JOptionPane.showMessageDialog(this, "Gagal menambahkan data:\n"
                    +"- Terdapat alfabet atau karakter spesial pada NIM");
        }
        else if (!(nim.length() == 10)){
            JOptionPane.showMessageDialog(this, "Gagal menambahkan data:\n"
                    +"- Banyak digit NIM tidak 10 (digit NIM saat ini: " +nim.length()
                    + ")");
        }
        else {
            boolean sudahAda = false;
            String namaDuplikat = "";

            for (Mahasiswa mhs : Mahasiswa.mahasiswas) {
                if (mhs.getNim().equals(nim)) {
                    sudahAda = true;
                    namaDuplikat = mhs.getNama();
                    break;
                }
            }
            if (sudahAda && !isDalamUpdate) {
                JOptionPane.showMessageDialog(this,"Gagal menambahkan data:\n" +
                    "- NIM sudah terdaftar atas nama: " + namaDuplikat);
            } else {
                if (isDalamUpdate){
                    Mahasiswa teredit = new Mahasiswa(nama, nim, prodi, 
                            jenisKelamin, isActive);
                    Mahasiswa.mahasiswas.set(barisTerpilih, teredit);
                    
                    JOptionPane.showMessageDialog(this, "Data mahasiswa " +nama+
                            " berhasil di-update!");
                    isDalamUpdate = false;                    
                    
                    LihatDataPanel panelLihat = new LihatDataPanel(mainFrame);
                    mainFrame.changeMainPanel(panelLihat);
                    tambahDataLabel.setText("Tambah Data Mahasiswa");
                    return; //biar yang dibawah ga ke run
                }
                Mahasiswa baru = new Mahasiswa(nama, nim, prodi, jenisKelamin,
                        isActive);
                Mahasiswa.mahasiswas.add(baru);

                JOptionPane.showMessageDialog(this, 
                        "Data mahasiswa berhasil ditambahkan!");
                clearForm();
            }
        }               
        
    }//GEN-LAST:event_kirimButtonActionPerformed

    private void namaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox aktifCheckBox;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton kirimButton;
    private javax.swing.JRadioButton lakiLakiRadioButton;
    private javax.swing.JTextField namaTextField;
    private javax.swing.JTextField nimTextField;
    private javax.swing.JRadioButton perempuanRadioButton;
    private javax.swing.JComboBox<String> prodiComboBox;
    private javax.swing.JLabel tambahDataLabel;
    // End of variables declaration//GEN-END:variables
}
