/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.gui2;

import javax.swing.JOptionPane;

/**
 *
 * @author fikry
 */
public class TambahDataPanel extends javax.swing.JPanel {

    /**
     * Creates new form TambahDataPanel
     */
    public TambahDataPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        namaTextField = new javax.swing.JTextField();
        nimTextField = new javax.swing.JTextField();
        prodiComboBox = new javax.swing.JComboBox<>();
        aktifCheckBox = new javax.swing.JCheckBox();
        lakiLakiRadioButton = new javax.swing.JRadioButton();
        perempuanRadioButton = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Tambah Data Mahasiswa");

        jLabel2.setText("Nama");

        jLabel3.setText("NIM");

        jLabel4.setText("Prodi");

        jLabel5.setText("Jenis Kelamin");

        jLabel6.setText("Status");

        prodiComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "S1 Teknik  Informatika", "S1 Teknik Elektro", "D3 Teknik Elektro" }));

        aktifCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        aktifCheckBox.setText("Aktif");

        lakiLakiRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(lakiLakiRadioButton);
        lakiLakiRadioButton.setText("Laki laki");

        perempuanRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(perempuanRadioButton);
        perempuanRadioButton.setText("Perempuan");

        jButton1.setBackground(new java.awt.Color(51, 255, 255));
        jButton1.setText("Kirim");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(prodiComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(aktifCheckBox)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lakiLakiRadioButton)
                                        .addGap(35, 35, 35)
                                        .addComponent(perempuanRadioButton))
                                    .addComponent(jButton1))
                                .addGap(0, 85, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(70, 70, 70)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(namaTextField)
                            .addComponent(nimTextField))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(namaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nimTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(prodiComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lakiLakiRadioButton)
                    .addComponent(perempuanRadioButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(aktifCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String nama = namaTextField.getText().trim();
        String nim = nimTextField.getText().trim();
        String prodi = (String) prodiComboBox.getSelectedItem();

        String jenisKelamin = "";
        if (lakiLakiRadioButton.isSelected()) {
            jenisKelamin = "Laki laki";
        } else if (perempuanRadioButton.isSelected()) {
            jenisKelamin = "Perempuan";
        }

        boolean isActive = aktifCheckBox.isSelected();

        if (nama.isEmpty()){
            JOptionPane.showMessageDialog(this, "Nama wajib diisi", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (nim.isEmpty()){
            JOptionPane.showMessageDialog(this, "NIM wajib diisi", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            Long.parseLong(nim);
        } catch (NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "NIM harus berupa angka", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (jenisKelamin.isEmpty()){
            JOptionPane.showMessageDialog(this, "Pilih jenis kelamin", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (Mahasiswa.nimExists(nim)){
            JOptionPane.showMessageDialog(this, "NIM sudah ada di database", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Mahasiswa mahasiswa = new Mahasiswa(nama, nim, prodi, jenisKelamin, isActive);
        Mahasiswa.mahasiswas.add(mahasiswa);

        JOptionPane.showMessageDialog(this, "Sukses menambahkan data mahasiswa " + nama);
        clearForm();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void clearForm(){
        namaTextField.setText("");
        nimTextField.setText("");
        lakiLakiRadioButton.setSelected(false);
        perempuanRadioButton.setSelected(false);
        aktifCheckBox.setSelected(false);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox aktifCheckBox;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton lakiLakiRadioButton;
    private javax.swing.JTextField namaTextField;
    private javax.swing.JTextField nimTextField;
    private javax.swing.JRadioButton perempuanRadioButton;
    private javax.swing.JComboBox<String> prodiComboBox;
    // End of variables declaration//GEN-END:variables
}
